stages:
  - build
  - deploy
  - test

image: docker:20.10.5
services:
  - docker:20.10.5-dind

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/hello:gitlab-$CI_COMMIT_SHORT_SHA"

build-job:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - echo "Docker image $DOCKER_IMAGE successfully built and pushed."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

tester:
    stage: test
    before_script:
        - apk add --update curl && rm -rf /var/cache/apk/*
    script:
        - docker run -it --rm --name python-api -p 5290:5290 -d registry.gitlab.com/sash3939/gitlab/hello:gitlab-62fd9fc1
        - sleep 10
        - curl http://docker:5290/get_info
        
        - docker ps
    needs: ["deploy-job"]